---
title: "Animacy Analysis of Zapotec RCs"
output:
  html_document:
    df_print: paged
---
```{r loadLibs, warning=FALSE, message=FALSE, echo=FALSE}
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(lme4)

target.df <- read.csv("zapotec-lao.csv")
```

```{r helperFunctions}
assignContrasts <- function(df){
  contrasts(df$Animacy) <- contr.helmert(3)
  contrasts(df$Animacy)[,1] <- c(-2/3,1/3,1/3)
  contrasts(df$Animacy)[,2] <- c(0,1/2,-1/2)
  colnames(contrasts(df$Animacy)) <- c("Human", "Elder")

  contrasts(df$SubClit) <- contr.sum(2)/2
  contrasts(df$OvOb) <- contr.sum(2)/2
  return(df)
}
```

```{r pSRC_by_animacy}
target.df %>% mutate(SRC=I(Parse=="SRC")) %>% group_by(Animacy, Item, Label, SRC) %>%
  summarize(n.resp=n()) %>% mutate(p_resp = (n.resp+0.5)/(1+sum(n.resp))) %>% filter(SRC==TRUE) %>%
  group_by(Label) %>%
  summarize(m_p = mean(p_resp), s_p = sd(p_resp), n_items = n(), se_p = s_p/sqrt(n_items)) -> animacy.tbl

pw <- position_dodge(width=0.1)
animacy.tbl %>%
  ggplot(aes(x=Label)) + 
  geom_pointrange(aes(y=m_p, ymin=m_p-se_p, ymax=m_p+se_p), position=pw, size=1.5) +
  scale_y_continuous(trans="logit") + geom_hline(yintercept=0.5) + 
  geom_hline(yintercept=seq(.3, 1, by=.1), lwd=0.1, col="darkgrey") +  
  xlab("Condition") + ylab("probability of Subject RC response") + ylim(0.3,1) +
  scale_color_colorblind() + theme_tufte()
```

```{r regression}
target.df %<>% assignContrasts

target.df %>%
  glmer(Parse ~ Animacy*OvOb*SubClit + (1 |Subject), family=binomial, data=.) %>% summary

```

```{r analysisByItem}
target.df %>% mutate(SRC=I(Parse=="SRC")) %>% group_by(Animacy, Item, SubClit, OvOb, SRC) %>%
  summarize(n.resp=n()) %>% mutate(p_resp = (n.resp+0.5)/(1+sum(n.resp))) %>% filter(SRC==TRUE) %>%
  ggplot(aes(x=Item, y=p_resp)) + geom_point(aes(col=Animacy, shape=SubClit, group=OvOb)) + scale_shape_circlefill() + scale_color_colorblind()
```

```{r RTsByItem}
target.df %>% group_by(Animacy, Label, Parse, Subject) %>% summarize(iRT=median(TouchRT)) %>%
  group_by(Animacy, Label, Parse) %>% summarize(mRT=mean(iRT), sRT=sd(iRT)/sqrt(n()), n=n()) %>%
  ggplot(aes(x=Animacy)) + facet_grid(.~Label) + 
  geom_pointrange(aes(y=mRT, ymin=mRT-sRT, ymax=mRT+sRT, size=log(n), col=Animacy, shape=Parse), position=pw) +
  geom_hline(yintercept=0.5) + scale_shape_circlefill() + scale_size_continuous(range = c(0.1,1.5)) + 
  xlab("Condition") + ylab("Touch RT (ms)") +
  scale_color_colorblind() + theme_tufte()
  
```

```{r AnimacyPlot}
target.df %<>% select(-Hierarchy)
animacy_hierarchy <- data.frame(Animacy=c("Animal", "Elder", "Human"), Hierarchy=c(1,3,2))
target.df %<>% left_join(., animacy_hierarchy)

target.df$Hierarchy %<>% factor
levels(target.df$Label) <- c("V=Cl","V+DP", "V=Cl+DP", "V+DP+Pron")
levels(target.df$Hierarchy) <- c("Animal","Human", "Elder")

target.df %>% mutate(SRC=I(Parse=="SRC")) %>% 
  group_by(Subject, Label, Hierarchy, SRC) %>%  summarize(n.resp=n()) %>%
  spread(key=SRC, value=n.resp) %>%
  mutate(n.tot = sum(c(`FALSE`,`TRUE`), na.rm=TRUE)) %>% rename(ORC = `FALSE`, SRC=`TRUE`) -> by_subj.tbl
by_subj.tbl$ORC[which(by_subj.tbl$SRC==by_subj.tbl$n.tot)] <- 0
by_subj.tbl$SRC[which(by_subj.tbl$ORC==by_subj.tbl$n.tot)] <- 0
by_subj.tbl %<>% mutate(p_SRC = (SRC+0.5)/(1+n.tot))

by_subj.tbl %>% 
  group_by(Label, Hierarchy) %>% summarize(p=mean(p_SRC), n.obs=n(), se=sd(p_SRC)/sqrt(n.obs)) -> animacy_summary.tbl

animacy_summary.tbl %>% ggplot(aes(x=Hierarchy, y=p)) -> animacy_plot

animacy_plot + geom_pointrange(aes(ymin=p-se, ymax=p+se, col=Label), size=1.25) + 
  scale_shape_circlefill() + theme_tufte() + ylab("probability of Subject RC response") + xlab("Argument Gender") +
  scale_color_colorblind() + ylim(0.001,0.999) + scale_y_continuous(trans="logit") + ylim(0.4,0.9) + 
  geom_hline(yintercept=0.5, width=0.5, col="darkgrey")
```

```{r AnimacyModel}

glm(Parse ~ Hierarchy*SubClit, data=target.df, family=binomial) %>% summary


```
